# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SettingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.SettingsButton.setObjectName("SettingsButton")
        self.horizontalLayout.addWidget(self.SettingsButton, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.LibraryTab = QtWidgets.QWidget()
        self.LibraryTab.setObjectName("LibraryTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LibraryTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LibraryToolBox = QtWidgets.QToolBox(self.LibraryTab)
        self.LibraryToolBox.setObjectName("LibraryToolBox")
        self.LibrarySablePage = QtWidgets.QWidget()
        self.LibrarySablePage.setGeometry(QtCore.QRect(0, 0, 758, 385))
        self.LibrarySablePage.setObjectName("LibrarySablePage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.LibrarySablePage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LibraryStableListWidget = QtWidgets.QListWidget(self.LibrarySablePage)
        self.LibraryStableListWidget.setObjectName("LibraryStableListWidget")
        self.verticalLayout_7.addWidget(self.LibraryStableListWidget)
        self.LibraryToolBox.addItem(self.LibrarySablePage, "")
        self.LibraryDailyPage = QtWidgets.QWidget()
        self.LibraryDailyPage.setGeometry(QtCore.QRect(0, 0, 98, 91))
        self.LibraryDailyPage.setObjectName("LibraryDailyPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.LibraryDailyPage)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.LibraryDailyListWidget = QtWidgets.QListWidget(self.LibraryDailyPage)
        self.LibraryDailyListWidget.setObjectName("LibraryDailyListWidget")
        self.verticalLayout_9.addWidget(self.LibraryDailyListWidget)
        self.LibraryToolBox.addItem(self.LibraryDailyPage, "")
        self.LibraryExperimentalPage = QtWidgets.QWidget()
        self.LibraryExperimentalPage.setGeometry(QtCore.QRect(0, 0, 98, 91))
        self.LibraryExperimentalPage.setObjectName("LibraryExperimentalPage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.LibraryExperimentalPage)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.LibraryExperimentalListWidget = QtWidgets.QListWidget(self.LibraryExperimentalPage)
        self.LibraryExperimentalListWidget.setObjectName("LibraryExperimentalListWidget")
        self.verticalLayout_8.addWidget(self.LibraryExperimentalListWidget)
        self.LibraryToolBox.addItem(self.LibraryExperimentalPage, "")
        self.verticalLayout.addWidget(self.LibraryToolBox)
        self.tabWidget.addTab(self.LibraryTab, "")
        self.DownloadsTab = QtWidgets.QWidget()
        self.DownloadsTab.setObjectName("DownloadsTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.DownloadsTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DownloadsToolBox = QtWidgets.QToolBox(self.DownloadsTab)
        self.DownloadsToolBox.setObjectName("DownloadsToolBox")
        self.DownloadsStablePage = QtWidgets.QWidget()
        self.DownloadsStablePage.setGeometry(QtCore.QRect(0, 0, 98, 91))
        self.DownloadsStablePage.setObjectName("DownloadsStablePage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.DownloadsStablePage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.DownloadsStableListWidget = QtWidgets.QListWidget(self.DownloadsStablePage)
        self.DownloadsStableListWidget.setObjectName("DownloadsStableListWidget")
        self.verticalLayout_4.addWidget(self.DownloadsStableListWidget)
        self.DownloadsToolBox.addItem(self.DownloadsStablePage, "")
        self.DownloadsDailyPage = QtWidgets.QWidget()
        self.DownloadsDailyPage.setGeometry(QtCore.QRect(0, 0, 98, 91))
        self.DownloadsDailyPage.setObjectName("DownloadsDailyPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.DownloadsDailyPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.DownloadsDailyListWidget = QtWidgets.QListWidget(self.DownloadsDailyPage)
        self.DownloadsDailyListWidget.setObjectName("DownloadsDailyListWidget")
        self.verticalLayout_5.addWidget(self.DownloadsDailyListWidget)
        self.DownloadsToolBox.addItem(self.DownloadsDailyPage, "")
        self.DownloadsExperimentalPage = QtWidgets.QWidget()
        self.DownloadsExperimentalPage.setGeometry(QtCore.QRect(0, 0, 98, 91))
        self.DownloadsExperimentalPage.setObjectName("DownloadsExperimentalPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.DownloadsExperimentalPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.DownloadsExperimentalListWidget = QtWidgets.QListWidget(self.DownloadsExperimentalPage)
        self.DownloadsExperimentalListWidget.setObjectName("DownloadsExperimentalListWidget")
        self.verticalLayout_6.addWidget(self.DownloadsExperimentalListWidget)
        self.DownloadsToolBox.addItem(self.DownloadsExperimentalPage, "")
        self.verticalLayout_3.addWidget(self.DownloadsToolBox)
        self.tabWidget.addTab(self.DownloadsTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.LibraryToolBox.setCurrentIndex(0)
        self.DownloadsToolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SettingsButton.setText(_translate("MainWindow", "Settings"))
        self.LibraryToolBox.setItemText(self.LibraryToolBox.indexOf(self.LibrarySablePage), _translate("MainWindow", "Stable Releases"))
        self.LibraryToolBox.setItemText(self.LibraryToolBox.indexOf(self.LibraryDailyPage), _translate("MainWindow", "Daily Builds"))
        self.LibraryToolBox.setItemText(self.LibraryToolBox.indexOf(self.LibraryExperimentalPage), _translate("MainWindow", "Experimental Branches"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LibraryTab), _translate("MainWindow", "Library"))
        self.DownloadsToolBox.setItemText(self.DownloadsToolBox.indexOf(self.DownloadsStablePage), _translate("MainWindow", "Stable Releases"))
        self.DownloadsToolBox.setItemText(self.DownloadsToolBox.indexOf(self.DownloadsDailyPage), _translate("MainWindow", "Daily Builds"))
        self.DownloadsToolBox.setItemText(self.DownloadsToolBox.indexOf(self.DownloadsExperimentalPage), _translate("MainWindow", "Experimental Branches"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DownloadsTab), _translate("MainWindow", "Downloads"))

import resources.resources_rc
